import Head from "next/head";
import styles from "../styles/Home.module.css";
import MainMenu from "../components/mainMenu";

export default function Home() {
  return (
    <div className={styles.container}>
      {/* Head tag  */}
      <Head>
        <title>Gabriel's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainMenu />
    </div>
  );
}
